In [44]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [45]:
# Manually fixed the values of M, F and I to 0.0, 0.1 and 0.2 so that they can be loaded into the
# dataset
dataset = np.loadtxt('/Users/param/Downloads/abalone.data', delimiter=',')
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:8]
y = dataset[:,8]
y = y.astype(int)


(4177, 9)


In [46]:
X

array([[0.    , 0.455 , 0.365 , ..., 0.2245, 0.101 , 0.15  ],
       [0.    , 0.35  , 0.265 , ..., 0.0995, 0.0485, 0.07  ],
       [0.1   , 0.53  , 0.42  , ..., 0.2565, 0.1415, 0.21  ],
       ...,
       [0.    , 0.6   , 0.475 , ..., 0.5255, 0.2875, 0.308 ],
       [0.1   , 0.625 , 0.485 , ..., 0.531 , 0.261 , 0.296 ],
       [0.    , 0.71  , 0.555 , ..., 0.9455, 0.3765, 0.495 ]])

In [47]:
y

array([15,  7,  9, ...,  9, 10, 12])

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2499, random_state=42)

In [49]:
X_train.shape

(3133, 8)

In [50]:
X_test.shape

(1044, 8)

In [53]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train) 
KNeighborsClassifier(...)
print(neigh.predict(X_test))

[ 9  8 12 ...  9  9  9]


In [54]:
print(y_test)

[ 9  8 16 ...  9  8  9]
